### ISSUE TITLE
Performance issue with count index

### ISSUE THREAD

**Issue by ccalvo-genasys** [dgraph-io/dgraph-docs#272]
When we add count index in our schema, the insertion of new tuples is very slow. Without count index we have around 50000 insertions/sec, but we add the count index, we insertions falls to 100 insertions/sec.
We think this is a bug, but we are not sure.
Thanks in advance

**Comment by ccalvo-genasys** [comment]
We are going to use the correct channel

**Comment by danielmai** [comment]
Thanks @ccalvo-genasys. I've replied to [your topic on Discuss](https://discuss.dgraph.io/t/performance-issue-with-count-index/16098/2?u=dmai).
