### ISSUE TITLE
DGRAPH learn - Introduction to Dgraph for SQL Users - BROKEN REDIRECTION LINK

### ISSUE THREAD

**Issue by lafusew** [dgraph-io/dgraph-docs#279]
Hey, oppening this issue just to let you know that there is a broken link on a "Next Page" button

The [Count Results](https://dgraph.io/learn/courses/datamodel/sql-to-dgraph/develop/read-data/count-results/) page's next button redirects to : https://dgraph.io/courses/datamodel/sql-to-dgraph/develop/read-data/paginate-results/

And it should redirect to: https://dgraph.io/learn/courses/datamodel/sql-to-dgraph/develop/read-data/paginate-results/

Dunno if oppening an issue here is the correct thing to do but just wanted to let u know

**Comment by danielmai** [comment]
Thanks for reporting this issue, @lafusew! The links are fixed now. Feel free to re-open if you're still seeing the issue.
