### ISSUE TITLE
Set contribution rules (RFC)

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph-docs#293]
Any modification outside of these rules the PR will be refused.

 1 - TODO -> Indentation of DQL, GraphQL and other code needs to be standardized(e.g: Tabs vs spaces - we need choose one and why). Because there can be no indentation conflict, if each one imposes their own way of working it becomes a mess. Each one will, for example, want to "repair" the previous indentation at their pleasure. It is not right.

2 - Modifications to current documentation content should have a clear and objective reason. If it's just a typo, it's valid without explanation. But any amendment that changes the concept must be rejected. In that case, please create something new to add in alignment with the context. Or explain how and why the change is needed.

cc @skrdgraph

**Comment by nswamy** [comment]
Can we use some linter ? that can be applied and validated as a part of PR test ?

**Comment by MichelDiz** [comment]
Ideally, we should have standards and the contributor have knowledge about them. A linter and etc would just be a rearguard. We can have triggers from gh actions to ask for changes automatically.
