### ISSUE TITLE
Algolia search does not work for docs of older versions

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#295]
Currently, documentation search only works for the docs' latest version (v21.12). I think the older versions are not indexed by algolia.

https://user-images.githubusercontent.com/69668484/193918501-03eaca11-996a-4a68-b71a-e92810b3e97e.mov

**Comment by Rajakavitha1** [comment]
Addressed in https://github.com/dgraph-io/dgraph-docs/pull/415 and https://github.com/dgraph-io/dgraph-docs/pull/417. Closing this issue for now. Please feel free to reopen if any other changes need to be made.
