### ISSUE TITLE
Back button redirects to wrong page on Deployment and Management Overview

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#296]
The back button in https://dgraph.io/docs/deploy/overview/ directs to the wrong (?) page. This page is the first page of this section (Deploy & Manage), but the back button redirects to "Ports Usage", which is a page somewhere further down in the same section. I'm not sure what's the intended behavior here though.

<img width="1552" alt="Screen Shot 2022-10-06 at 11 47 46" src="https://user-images.githubusercontent.com/69668484/194396212-5abc7db9-5f43-4044-8d09-5d045a638074.png">

**Comment by MichelDiz** [comment]
This bug is related to #299

It is a bug in the script used to modify Hugo theme.
