### ISSUE TITLE
Missing CGO_ENABLED=0 in "Building from Source" installation

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#298]
https://dgraph.io/docs/deploy/download/#building-from-source

In here, the command given is `make install`, but i found that running that gives an error (on an amd64 linux). But it is fine when I add the `CGO_ENABLED=0` flag (something to do with jemalloc?).

So perhaps we should change it to `CGO_ENABLED=0 make install`.

![Screen Shot 2022-10-06 at 15 59 24](https://user-images.githubusercontent.com/69668484/194433895-b2471e45-951a-46a2-99d2-643a0f52edff.png)

**Comment by MichelDiz** [comment]
@joshua-goldstein can you help to clarify?

**Comment by joshua-goldstein** [comment]
Hi @kevinmingtarja , thanks for catching this.  Take a look at the readme for dgraph (on Github).  We updated it to the following:
```
sudo apt-get update
sudo apt-get install build-essential
```
which should install the necessary library.  The page in the docs should also be updated to reflect this @MichelDiz .

**Comment by kevinmingtarja** [comment]
Ah okay, so we should refactor this section to follow the one in the dgraph README.

<img width="826" alt="Screen Shot 2022-10-11 at 12 32 40" src="https://user-images.githubusercontent.com/69668484/195182498-1f7e631c-8faf-4657-b876-273e49c4a174.png">

**Comment by matthewmcneely** [comment]
And check out the fresh README in at https://github.com/dgraph-io/dgraph/tree/matthewmcneely/update-readme-and-contributing

**Comment by MichelDiz** [comment]
@kevinmingtarja if you gonna do this, we need it today.
