### ISSUE TITLE
Wrong next page on Download Dgraph page

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#299]
The next page of https://dgraph.io/docs/deploy/download/ should be "Configuration", but instead it is "Logging".

<img width="1552" alt="Screen Shot 2022-10-06 at 16 16 39" src="https://user-images.githubusercontent.com/69668484/194435326-f292d029-93b1-44db-991b-b140dcb586d5.png">

**Comment by Rajakavitha1** [comment]
Hi @kevinmingtarja closing this issue for now. in the recent docs revamp we have moved Download under installation and the related pages appear correct. Please feel free to reopen if any other issue needs to be addressed.
