### ISSUE TITLE
dgraph-ratel command in Single Host Setup

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#300]
https://dgraph.io/docs/deploy/single-host-setup/#run-dgraphs-ratel-ui

iirc `dgraph-ratel` is not part of the dgraph binary right? So I think it does not make sense to still have this command here, especially since in the previous ["Download Dgraph" ](https://dgraph.io/docs/deploy/download/) section, we don't tell the readers about downloading Ratel.

Edit: Or we should follow the one at the later part of this page (https://dgraph.io/docs/deploy/single-host-setup/#run-dgraphs-ratel-ui-1), which is the second image.

<img width="1552" alt="Screen Shot 2022-10-06 at 17 20 18" src="https://user-images.githubusercontent.com/69668484/194441049-82a25602-e515-4eec-b627-9448dbcb3b4b.png">

<img width="1552" alt="Screen Shot 2022-10-06 at 17 24 45" src="https://user-images.githubusercontent.com/69668484/194441402-a83d5da8-c482-4c75-8b96-b84154636eb6.png">

**Comment by MichelDiz** [comment]
@kevinmingtarja please review https://github.com/dgraph-io/dgraph-docs/pull/321
