### ISSUE TITLE
Suggestion: Generalize "Run using Docker Compose" to not only AWS

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#301]
https://dgraph.io/docs/deploy/single-host-setup/#run-using-docker-compose-on-single-aws-instance

Right now, this part of using docker-compose to run dgraph on a single host is only mentioning AWS, but would it make more sense to not mention AWS, since docker-compose can be used anywhere.

<img width="1552" alt="Screen Shot 2022-10-06 at 17 29 13" src="https://user-images.githubusercontent.com/69668484/194441783-56a8eadc-4ff9-4b0d-92d2-3e225a9633b2.png">

**Comment by MichelDiz** [comment]
@kevinmingtarja do you want to pick this one? or delay this?

**Comment by Rajakavitha1** [comment]
@kevinmingtarja !!! Our instructions are now generic and specific to AWS. This has been addressed in https://github.com/dgraph-io/dgraph-docs/pull/439. Please feel free to reopen if any other changes need to be made.
