### ISSUE TITLE
Refactor any examples that's using docker-machine commands

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#302]
https://dgraph.io/docs/deploy/single-host-setup/#run-using-docker-compose-on-single-aws-instance
https://dgraph.io/docs/deploy/multi-host-setup/

These two sections still uses the `docker-machine` command, which is depecrated (https://github.com/docker/machine/issues/4537) and replaced by Docker Desktop now. So, we should refactor these examples so that the readers are not confused.

**Comment by Rajakavitha1** [comment]
@kevinmingtarja  closing this issue because this has been addressed in https://github.com/dgraph-io/dgraph-docs/pull/439.
