### ISSUE TITLE
Command to set up encryption key file under the document Encryption at rest does not work.

### ISSUE THREAD

**Issue by SashaDgraph** [dgraph-io/dgraph-docs#304]
The key generation command, when executed, gives gives an error and does not produce a key with the specified length.

**Comment by SashaDgraph** [comment]
https://dgraph.io/docs/enterprise-features/encryption-at-rest/

This is the page referred to in the title.

**Comment by SashaDgraph** [comment]
This is the given command for key generation:

tr -dc 'a-zA-Z0-9' < /dev/urandom | dd bs=1 count=32 of=enc_key_file

It may return the following error - 

 tr: Illegal byte sequence 

and does not generate a key of the specified length (here, 32). 

If this error occurs, we need to run the following line:
export LC_CTYPE = C

before we run the key generation command. Please verify this method and make the necessary changes.

**Comment by MichelDiz** [comment]
For me it is working.
What distro are you using?

If the solution is `export LC_CTYPE = C` we need to know why and them add to docs.

![image](https://user-images.githubusercontent.com/6570955/194665821-360bb530-1ef4-4f66-91ca-351e55cd2e06.png)

**Comment by SashaDgraph** [comment]
> For me it is working. What distro are you using?
> 
> If the solution is `export LC_CTYPE = C` we need to know why and them add to docs.
> 
> ![image](https://user-images.githubusercontent.com/6570955/194665821-360bb530-1ef4-4f66-91ca-351e55cd2e06.png)
> 
> ```
> micheldiz@DESKTOP-M2T9D7Q:~/tmp$ cat enc_key_file
> DgdkkomuvlMTDQPVBjmuDtTUIuUj92GH
> ```

The following is the screenshot of the error that I get. That error is resolved by the command LC_CTYPE=C.
<img width="1158" alt="Screen Shot 2022-10-08 at 9 59 59 PM" src="https://user-images.githubusercontent.com/110432097/194735764-f2074057-9f63-4b1c-89ee-d9ec0ecd3885.png">

**Comment by joshua-goldstein** [comment]
I also have the same issue on an M1 Mac.  I believe the issue has something to do with character encoding.  
From `man environ`:
```
LC_CTYPE     Locale to be used for character classification (letter, space,
                  digit, etc.) and for interpreting byte sequences as multibyte
                  characters.
```

As opposed to calling `export` this works on my M1:
```
> LC_CTYPE=C; tr -dc 'a-zA-Z0-9' < /dev/urandom | dd bs=1 count=32 of=enc_key_file
32+0 records in
32+0 records out
32 bytes transferred in 0.005538 secs (5778 bytes/sec)
> cat enc_key_file 
nRsNY7ohWjOHslSywDaieB0hMhjpxAJS%  
```

**Comment by MichelDiz** [comment]
Thanks guys for investigating this.

@skrdgraph Do you think we should document this? It is a macOS-only error. And we don't officially support Darwin. Unless we do in the future.

**Comment by Rajakavitha1** [comment]
Closing this issue because it has been addressed in https://github.com/dgraph-io/dgraph-docs/pull/334
