### ISSUE TITLE
In Deploy and Manage > Security > TLS > Dgraph Certificate Management Tool 

### ISSUE THREAD

**Issue by SashaDgraph** [dgraph-io/dgraph-docs#306]
If, after following the path in the title, you click on TLS Configuration Documentation, it leads you to a Get Started with Dgraph page, so it is not the right link.

**Comment by SashaDgraph** [comment]
https://dgraph.io/docs/deploy/tls-configuration/ 
This is the document which has a Dgraph Certificate Management Tool Section

**Comment by MichelDiz** [comment]
The Note is pointing to a non-existent doc. to => `https://dgraph.io/docs/v1.0.7/deploy/#tls-configuration`

Resolution: Find the old reference, analyze what it is doing.
Or point to the old PR(in the main repository).
Or find the reference in the current documentation if it still exists.
