### ISSUE TITLE
Quotation marks needed for superflags

### ISSUE THREAD

**Issue by joshua-goldstein** [dgraph-io/dgraph-docs#308]
[See my PR here](https://github.com/dgraph-io/dgraph-docs/pull/289)

In our docs we do not show quotes around superflags.  However commands like

`dgraph zero --audit output=audit-log-dir;compress=false;encrypt-file=enc-key`

will fail to execute correctly without the quotes, because only the first flag will get parsed.  In my PR I add quotes to a few commands related to audit logging.  Presumably this is an issue elsewhere.  I am not sure if it would be better to add double or single quotes.

**Comment by MichelDiz** [comment]
@joshua-goldstein closing this. Next time you can add a comment in the PR e.g. "Fix #000_PR_NUMER" and this issue will be closed automatically.
