### ISSUE TITLE
fix Restrict Mutation Operations command

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#311]
https://dgraph.io/docs/deploy/dgraph-administration/#restrict-mutation-operations

For the second command, correct me if i'm wrong but I don't think `mutations-nquad=1000000` is relevant to the current context, as it is only demonstrating `mutations=strict`. So I think we should remove it to not make readers confused.

There is also a missing quotation mark at the end of `Enforce a strict schema by setting --limit "mutations=strict`.

<img width="826" alt="Screen Shot 2022-10-11 at 12 55 21" src="https://user-images.githubusercontent.com/69668484/195186251-5eb42a3c-d587-4a84-b119-83098dab000f.png">

**Comment by MichelDiz** [comment]
Maybe we should rename this topic from "Restrict Mutation Operations" to something like "Limiting operations" and add more other flags. Because there are others that don't seem to be being explored by the docs.

**Comment by MichelDiz** [comment]
@kevinmingtarja I'll delay this. If you work on it today, good!
