### ISSUE TITLE
Fix Secure Alter Operations commands

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#312]
https://dgraph.io/docs/deploy/dgraph-administration/#secure-alter-operations

The two bottommost commands has the wrong port number, we should set it to the default which is `8080`.

<img width="826" alt="Screen Shot 2022-10-11 at 13 05 08" src="https://user-images.githubusercontent.com/69668484/195188027-18282205-1dfe-473d-a052-2cf370cd3b5b.png">

**Comment by MichelDiz** [comment]
This is terrible, this typo has been there for two years!
