### ISSUE TITLE
Export API is no longer async

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#314]
https://dgraph.io/docs/deploy/dgraph-administration/#export-database

Here, it says that `Since v21.03, the export and backup APIs are asynchronous`. But this is incorrect for export. Since `v21.03.1`, export is synchronous again.

<img width="1552" alt="Screen Shot 2022-10-11 at 15 35 07" src="https://user-images.githubusercontent.com/69668484/195210890-4fd3b950-985e-4671-b237-0758774cf206.png">

This is further verified by the fact that `worker.Tasks.Enqueue()` only shows up once in the codebase, which is for backup only.

![Screen Shot 2022-10-11 at 15 28 58](https://user-images.githubusercontent.com/69668484/195210993-00fb5418-342d-4845-b108-e21cd20eb49e.png)

Consequently, we also need to refactor the [Check queued tasks](https://dgraph.io/docs/deploy/dgraph-administration/#check-queued-tasks) section a bit to not mention export.

**Comment by damonfeldman** [comment]
When I do an export from the cloud GUI, however, I get a message saying "Task has been created" then the exports list reports the export as "pending" and later it switches to "completed." My guess is that the proxy is doing the work and the background processing is in that process - have we checked there?

<img width="420" alt="image" src="https://user-images.githubusercontent.com/700633/206450218-9ca9bc82-4afd-41ac-8955-b8b88b01b525.png">

**Comment by Rajakavitha1** [comment]
Hi @damonfeldman  can you please confirm if this has been addressed as documented here: https://deploy-preview-355--dgraph-docs-repo.netlify.app/howto/exportdata/export-data/. It would be great if you could review and state your approval for https://github.com/dgraph-io/dgraph-docs/pull/355

**Comment by Rajakavitha1** [comment]
This has been addressed in the PR #355
