### ISSUE TITLE
Wrong wal directory for zeros in Upgrade database section

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#315]
https://dgraph.io/docs/deploy/dgraph-administration/#upgrade-database

The wal directory for zeros should be `zw`, not `w`

<img width="782" alt="Screen Shot 2022-10-11 at 16 17 17" src="https://user-images.githubusercontent.com/69668484/195215643-6c94039a-0c73-4c28-adbf-1dcbce327484.png">

**Comment by MichelDiz** [comment]
I believe you are confusing. This part talks about the flag to use. The Dgraph binary the flag is called "-w" in fact. However, the directory name for zero is wz. This part of the doc doesn't say that the directory name is w, just that the flag is -w.

![image](https://user-images.githubusercontent.com/6570955/195216448-02357076-cabb-43ef-a82d-76e21b9874f0.png)

**Comment by kevinmingtarja** [comment]
Ah right, thanks for pointing it out @MichelDiz , I was thinking of the wrong thing.
