### ISSUE TITLE
Broken link in Bulk Loader section

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/dgraph-docs#316]
https://dgraph.io/docs/deploy/fast-data-loading/bulk-loader/

The link (`read some technical details`) here points to https://blog.dgraph.io/post/bulkloader/, which just redirects to https://dgraph.io/blog/ instead of the intended blog post (due to the redirection?). We should replace with https://dgraph.io/blog/post/bulkloader/.

<img width="782" alt="Screen Shot 2022-10-11 at 20 20 00" src="https://user-images.githubusercontent.com/69668484/195242125-2af90680-645d-4c5b-9118-c85863e76092.png">

**Comment by MichelDiz** [comment]
This is a redirection problem. We either fix the docs or fix the redirections.

cc @darkn3rd
