### ISSUE TITLE
Fix Dgraph Release Page

### ISSUE THREAD

**Issue by joshua-goldstein** [dgraph-io/dgraph-docs#329]
The Dgraph releases pages needs a major revamp: https://dgraph.io/docs/releases/

In particular
- 21.12 should be marked as deprecated
- What is end of life of 21.03?  On doc it writes March 2022 but we are still supporting it
- 22.0.0 should be added

**Comment by MichelDiz** [comment]
@skrdgraph @akon-dey we also need to check the end of life of 21.12 and set the new one.
