### ISSUE TITLE
Remove Ludicrous Mode in docs

### ISSUE THREAD

**Issue by skrdgraph** [dgraph-io/dgraph-docs#408]
Related to this PR https://github.com/dgraph-io/dgraph/pull/8612

The docs need correspond changes.

**Comment by rderbier** [comment]
@skrdgraph is the change to just remove all references to ludicrous mode ?

**Comment by Rajakavitha1** [comment]
> @skrdgraph is the change to just remove all references to ludicrous mode ?

@skrdgraph  should we just remove this page in the docs: https://dgraph.io/docs/deploy/ludicrous-mode/
