### ISSUE TITLE
Add feedback mechanism in template

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph-docs#412]

**Comment by rderbier** [comment]
Page template has "Ask a question" (to discuss) and "Edit the page".
We should have feedback mechanism 
- is it usefull (vote)
- report issue -> to github with automatic reference of the page.
- feedback should probably go to github to with automatic reference of the page.
Review if edit the page is creating a PR ? what's the process.

**Comment by Rajakavitha1** [comment]
Hi @rderbier !!! Github has made it easy please check this: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by Rajakavitha1** [comment]
Hi @MichelDiz  and @rderbier just created a related PR: https://github.com/dgraph-io/hugo-docs/pull/115

**Comment by Rajakavitha1** [comment]
This has now been implemented by @rderbier
