### ISSUE TITLE
Docs: "removing a pod" lost in new docs version

### ISSUE THREAD

**Issue by damonfeldman** [dgraph-io/dgraph-docs#450]
The old page here: https://github.com/dgraph-io/dgraph-docs/blob/ed6f1dbb591234fa5c4eb704b593526b65a5050c/content/installation/kubernetes.md has a "removing a pod" section documenting how to use /removeNode and K8s delete to force a pod to be removed and rebuilt from a healthy pod with a correct p directory (rebuild in case of data issues on one node).

The removal process should be documented, perhaps in troubleshooting or how-to guides (or a link in troubleshooting about a bad p directory linked to the how to guide on removing an alpha)

**Comment by Rajakavitha1** [comment]
Hi @damonfeldman  closing this issue for now because this content has not been removed even the updates made to install section in the latest PR: https://github.com/dgraph-io/dgraph-docs/pull/439
