### ISSUE TITLE
Typo in DGraph Cloud Schema editor when deleting a predicate

### ISSUE THREAD

**Issue by nick-w-nick** [dgraph-io/dgraph-docs#629]
This may or may not be the right place to post this issue, but since the DGraph Cloud UI itself is not open source, this seemed like the right place as the docs are partially related to DGraph Cloud. Let me know if this issue should be created elsewhere instead.

I noticed when trying to delete a predicate on the DQL Schema tab on the Schema page in DGraph Cloud that the text that is shown in the confirmation modal has a typo. `permenetly` should be `permanently`.

![dgraph-cloud-delete-predicate-typo](https://github.com/dgraph-io/dgraph-docs/assets/43578531/b294f77a-56b4-4702-a6cb-c719e7fdf543)

I also think the text "The **type** will be permanently removed" is a bit misleading and should instead say "The **predicate** will be permanently removed". You can't outright delete a type from the UI in this way, so it's not like the modal is re-used for both operations. 

This issue is specifically to raise notice regarding the typo but just thought I'd make a suggestion regarding the wording while in this area as well.

Thanks!

**Comment by nick-w-nick** [comment]
@MichelDiz FYI, I can't recall if I ever verified if the issue was fully fixed after your reply, so I am not sure if it is a regression or not, but the issue does still seem to be present in the DGraph Cloud UI when deleting a predicate.

![dgraph-delete-predicate-typo](https://github.com/dgraph-io/dgraph-docs/assets/43578531/29afacfb-f320-4ee2-ab11-a4cbd312d325)

**Comment by MichelDiz** [comment]
@nick-w-nick I'm not working at Dgraph anymore. Maybe @rderbier or @damonfeldman can help you with this on the cloud product.
